config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/heal', to: 'pokemons#healall'
  get '/heal/:id', to: 'pokemons#heal', as: 'heal_pokemon'
  get '/heal-trainer/:id', to: 'pokemon_trainers#healall', as: 'heal_trainer'
  get '/heal-trainer/:id/:pokemon_id', to: 'pokemon_trainers#heal', as: 'heal_trainer_pokemon'

  resources :pokedexes
  resources :skills
  resources :pokemons do
    resources :pokemon_skills, only: [:create, :destroy]
  end
  resources :pokemon_battles do
    member do
      get :evolve_confirmation
      post :evolve_confirmation, to: 'pokemon_battles#evolve'
      get :skill_change
      post :change_skill
    end
  end
  resources :trainers do
    resources :pokemon_trainers, only: [:create, :destroy]
  end
end

app/models/pokemon_battle.rb
class PokemonBattle < ApplicationRecord
    belongs_to :pokemon1, class_name: "Pokemon", foreign_key: "pokemon1_id"
    belongs_to :pokemon2, class_name: "Pokemon", foreign_key: "pokemon2_id"
    belongs_to :winner, class_name: "Pokemon", foreign_key: "pokemon_winner_id", optional: true
    belongs_to :loser, class_name: "Pokemon", foreign_key: "pokemon_loser_id", optional: true

    has_many :logs, class_name: "PokemonBattleLog", foreign_key: "pokemon_battle_id", dependent: :destroy

    validate :same_pokemon
    validate :pokemon_health, on: :create
    validates :battle_type, inclusion: { in: ['Manual', 'vs AI', 'Auto'],
        message: "%{value} is not a valid battle type" }

    private
    def same_pokemon
        if pokemon1_id == pokemon2_id
            errors.add(:base, " Pokemon2 can't be same with Pokemon1")
        end
    end

    def pokemon_health
        if Pokemon.exists?(pokemon1_id) && Pokemon.exists?(pokemon2_id)
            @pokemon1 = Pokemon.find(pokemon1_id)
            @pokemon2 = Pokemon.find(pokemon2_id)
            if @pokemon1.current_health_point == 0 
                errors.add(:base, " Pokemon1 can't have 0 health to battle")
            end
            if @pokemon2.current_health_point == 0
                errors.add(:base, " Pokemon2 can't have 0 health to battle")
            end
        else  
            errors.add(:base, " Pokemon Not Found")
        end
    end
end

app/controllers/pokemon_battles_controller.rb
class PokemonBattlesController < ApplicationController
    add_breadcrumb "Home", :root_path
    add_breadcrumb "Pokemon Battles", :pokemon_battles_path

    def index
        @pokemon_battles = PokemonBattle.paginate(page: params[:page], :per_page => 15)
    end

    def new
        @pokemon_battle = PokemonBattle.new
        @pokemons = Pokemon.all.order(created_at: :asc).map{ |pokemon| [pokemon.name, pokemon.id] }
        add_breadcrumb "New", new_pokemon_battle_path
    end

    def create
        @pokemon1 = Pokemon.find(battle_params[:pokemon1_id])
        @pokemon2 = Pokemon.find(battle_params[:pokemon2_id])
        @pokemon_battle = PokemonBattle.new(battle_params)
        @pokemon_battle.pokemon1_max_health_point = @pokemon1.max_health_point
        @pokemon_battle.pokemon2_max_health_point = @pokemon2.max_health_point
        @pokemon_battle.battle_type = params[:commit]
        if @pokemon_battle.save
            flash[:success] = "Battle successfully created, Lets Fight!!"
            if params[:commit] == 'Auto'
                pokemon1_level = @pokemon_battle.pokemon1.level
                pokemon2_level = @pokemon_battle.pokemon2.level
                AiEngine.auto_battle(@pokemon_battle.id)
                if PokemonEvolution.evolve?(@pokemon_battle.id, pokemon1_level, pokemon2_level)
                    redirect_to evolve_confirmation_pokemon_battle_path(@pokemon_battle) and return
                end
            end
            redirect_to pokemon_battle_path(@pokemon_battle)
        else
            @pokemons = Pokemon.all.map{ |pokemon| [pokemon.name, pokemon.id] }
            render 'new'
        end
    end

    def show
        @pokemon_battle = PokemonBattle.find(params[:id])
        @skill1 = @pokemon_battle.pokemon1.pokemon_skills.map{ |s| [s.skill.name, s.skill_id]}
        @skill2 = @pokemon_battle.pokemon2.pokemon_skills.map{ |s| [s.skill.name, s.skill_id]}
        @logs = @pokemon_battle.logs
        add_breadcrumb "#{@pokemon_battle.pokemon1.name} vs #{@pokemon_battle.pokemon2.name}", pokemon_battle_path(@pokemon_battle)
    end

    def destroy
        @pokemon_battle = PokemonBattle.find(params[:id]).destroy
        flash[:success] = "Battle Deleted"
        redirect_to pokemon_battles_path
    end

    def update
        @pokemon_battle = PokemonBattle.find(params[:id])
        pokemon1_level = @pokemon_battle.pokemon1.level
        pokemon2_level = @pokemon_battle.pokemon2.level
        if params[:commit] == "Auto"
            AiEngine.auto_battle(@pokemon_battle.id)
            if PokemonEvolution.evolve?(@pokemon_battle.id, pokemon1_level, pokemon2_level)
                redirect_to evolve_confirmation_pokemon_battle_path(@pokemon_battle)
            else
                redirect_to pokemon_battle_path(@pokemon_battle)
            end
        else
            battle_engine = BattleEngine.new(battle_id: params[:id].to_i,pokemon_id: params[:attack][:pokemon_id].to_i, skill_id: params[:attack][:skill_id].to_i, action: params[:commit])
            if battle_engine.valid_next_turn?
                if battle_engine.next_turn!
                    battle_engine.save!
                    @pokemon_battle.reload
                    if @pokemon_battle.battle_type == 'vs AI' && @pokemon_battle.state == 'On Going'
                        AiEngine.ai_turn(@pokemon_battle.id)
                    end
                    if PokemonEvolution.evolve?(@pokemon_battle.id, pokemon1_level, pokemon2_level)
                        redirect_to evolve_confirmation_pokemon_battle_path(@pokemon_battle)
                    else
                        redirect_to pokemon_battle_path(@pokemon_battle)
                    end
                else
                    flash.now[:danger] = "Skill Not Found or Skill PP is depleted"
                    @skill1 = @pokemon_battle.pokemon1.pokemon_skills.map{ |s| [s.skill.name, s.skill_id]}
                    @skill2 = @pokemon_battle.pokemon2.pokemon_skills.map{ |s| [s.skill.name, s.skill_id]}
                    @logs = @pokemon_battle.logs
                    render 'show'
                end
            else
                flash.now[:danger] = "Move not valid"
                @skill1 = @pokemon_battle.pokemon1.pokemon_skills.map{ |s| [s.skill.name, s.skill_id]}
                @skill2 = @pokemon_battle.pokemon2.pokemon_skills.map{ |s| [s.skill.name, s.skill_id]}
                @logs = @pokemon_battle.logs
                render 'show'
            end
        end
    end

    def evolve_confirmation
        @pokemon_battle = PokemonBattle.find(params[:id])
        if !@pokemon_battle.pokemon_winner_id.nil?
            @pokemon = Pokemon.find(@pokemon_battle.pokemon_winner_id)
            if EvolutionList.exists?(pokedex_from_name: @pokemon.pokedex.name)
                @evolve_to = EvolutionList.find_by(pokedex_from_name: @pokemon.pokedex.name)
                @pokemon_evolve_to = Pokedex.find_by(name: @evolve_to.pokedex_to_name)
            end
        else
            redirect_to pokemon_battle_path(@pokemon_battle)
        end
    end

    def evolve
        @pokemon_battle = PokemonBattle.find(params[:id])
        if params[:commit] == 'Yes'
            if !@pokemon_battle.pokemon_winner_id.nil?
                @pokemon = Pokemon.find(@pokemon_battle.pokemon_winner_id)
                if EvolutionList.exists?(pokedex_from_name: @pokemon.pokedex.name)
                    @evolve_to = EvolutionList.find_by(pokedex_from_name: @pokemon.pokedex.name)
                    @pokemon_evolve_to = Pokedex.find_by(name: @evolve_to.pokedex_to_name)
                    stats = PokemonEvolution.calculate_evolve_extra_stats(@pokemon.pokedex_id, @pokemon_evolve_to.id)
                    @pokemon.pokedex_id = @pokemon_evolve_to.id
                    @pokemon.max_health_point = @pokemon.max_health_point + stats.health
                    @pokemon.attack = @pokemon.attack + stats.attack
                    @pokemon.defence = @pokemon.defence + stats.defence
                    @pokemon.speed = @pokemon.speed + stats.speed
                    @pokemon.save!
                    redirect_to skill_change_pokemon_battle_path(@pokemon_battle)
                end
            else
                redirect_to pokemon_battle_path(@pokemon_battle)
            end
        else
            redirect_to pokemon_battle_path(@pokemon_battle)
        end
    end

    def skill_change
        @pokemon_battle = PokemonBattle.find(params[:id])
        @pokemon_skill = PokemonSkill.new
        @pokemon = Pokemon.find(@pokemon_battle.pokemon_winner_id)
        @current_skill = @pokemon.pokemon_skills.map{ |s| s.skill_id }
        @pokemon_skills = @pokemon.pokemon_skills.map{ |s| [s.skill.name, s.skill.id]}
        @skills = Skill.all.select{ |s| !@current_skill.include?(s.id) && s.element_type == @pokemon.pokedex.element_type }
        .map{|s| [s.name, s.id]}
    end

    def change_skill
        @pokemon_battle = PokemonBattle.find(params[:id])
        @pokemon = Pokemon.find(@pokemon_battle.pokemon_winner_id)
        if params[:change_skill][:skill_delete_id].present?
            @pokemon_skill = @pokemon.pokemon_skills.find_by(skill_id: params[:change_skill][:skill_delete_id])
            @pokemon_skill.destroy
            flash[:success] = "Skill removed from #{@pokemon.name}"
        end
        if params[:change_skill][:skill_add_id].present?
            @skill = Skill.find(params[:change_skill][:skill_add_id])
            @pokemon_skill = PokemonSkill.new(pokemon_id: @pokemon.id,skill_id: @skill.id, current_pp: @skill.max_pp)
            if @pokemon_skill.save
                flash[:success] = "Skill #{@skill.name} added to #{@pokemon.name}"
                redirect_to pokemon_battle_path(@pokemon_battle)
            else
                @current_skill = @pokemon.pokemon_skills.map{ |s| s.skill_id }
                @pokemon_skills = @pokemon.pokemon_skills.map{ |s| [s.skill.name, s.skill.id]}
                @skills = Skill.all.select{ |s| !@current_skill.include?(s.id) && s.element_type == @pokemon.pokedex.element_type }
                    .map{|s| [s.name, s.id]}
                render :skill_change
            end
        else
            flash[:success] = "No Skill added"
            redirect_to pokemon_battle_path(@pokemon_battle)
        end
    end

    private 
    def battle_params
        params.require(:pokemon_battle).permit(:pokemon1_id, :pokemon2_id)
    end
end

app/helpers/pokemon_battles_helper.rb
module PokemonBattlesHelper
end

app/views/pokemon_battles/evolve_confirmation.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2 class="text-center">Wait? <%= @pokemon.name %> are evolving!!</h2>
        </div>
        <div class="card-body">
            <div class="row" style="margin-top:10px">
                <div class="col-4">
                    <div class="container">
                        <div class="card">
                            <%= image_tag @pokemon.pokedex.image_url,size: "150x250", class: "card-img-top" %>
                            <div class="card-header form-header">
                                <h5 class="card-title text-center"><%= @pokemon.pokedex.name%></h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="d-flex align-items-center h-100">
                        <h2 class="mx-auto">>>>>>>>>>>></h2>
                    </div> 
                </div>
                <div class="col-4">
                    <div class="container">
                        <div class="card card-height">
                            <%= image_tag @pokemon_evolve_to.image_url,size: "150x250" , class: "card-img-top" %>
                            <div class="card-header form-header">
                                <h5 class="card-title text-center"><%= @pokemon_evolve_to.name%></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <%= form_for :evolve_confirmation, url: evolve_confirmation_pokemon_battle_path(@pokemon_battle) do |f| %>
                <div class="row form-header">
                    <h2 class="mx-auto">Do you want to evolve <%= @pokemon.name %>?</h2>
                </div>

                <div class="row form-footer">
                    <div class="col-md-6">
                        <%= f.submit "Yes", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
                    </div>
                    <div class="col-md-6">
                        <%= f.submit "Next Time", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
                    </div>
                </div>
            <% end %>
        </div>
</div>

app/views/pokemon_battles/index.html.erb
<div class="container">
    <div>
        <%= link_to "New Battle", new_pokemon_battle_path, class: "btn btn-primary"%>
    </div>
    <div class="card" style="margin-top: 15px; margin-bottom: 20px">
        <div class="card-header bg-primary border-primary text-white">Pokemon Battles</div>
        <div class="card-body">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr class="d-flex">
                        <th class="col-2 text-center">Pokemon 1</th>
                        <th class="col-2 text-center">Pokemon 2</th>
                        <th class="col-2 text-center">Turn</th>
                        <th class="col-2 text-center">Status</th>
                        <th class="col-4 text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @pokemon_battles.each do |pokemon_battle| %>
                        <tr class="d-flex">
                            <td class="col-2 text-center"><%= pokemon_battle.pokemon1.name %></td>
                            <td class="col-2 text-center"><%= pokemon_battle.pokemon2.name %></td>
                            <td class="col-2 text-center"><%= pokemon_battle.current_turn %></td>
                            <td class="col-2 text-center"><%= pokemon_battle.state %></td>
                            <td class="col-4 text-center">
                            <%= link_to "Show", pokemon_battle_path(pokemon_battle), class: "btn btn-info"%>
                            <%= link_to "Delete", pokemon_battle_path(pokemon_battle), method: :delete,
                                            data: { confirm: "You sure?" }, class: "btn btn-danger"%>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="clearfix card-footer">
            <%= will_paginate @pokemons, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "float-right" %>
        </div>
    </div>
</div>

app/views/pokemon_battles/new.html.erb
<div class="container">
    <div class="card" style="margin-top: 15px; margin-bottom: 20px">
        <%= form_for @pokemon_battle do |f| %>
        <div class="card-header">
            <div class="row">
                <h2 class="mx-auto">Select Pokemon</h2>
            </div>
            <%= render 'layouts/error_messages', object: @pokemon_battle %>
        </div>
        <div class="card-body">
            <div class="form-row form-group">
                <div class="col-6 text-center">
                    <%= f.label :pokemon1_id, class: "col-form-label" %>
                </div>
                <div class="col-6 text-center">
                    <%= f.label :pokemon2_id, class: "col-form-label" %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-6">
                    <%= f.select :pokemon1_id, @pokemons, {}, class: "form-control" %>
                </div>
                <div class="col-6">
                    <%= f.select :pokemon2_id, @pokemons, {}, class: "form-control" %>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-md-4">
                    <%= f.submit "Manual", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
                </div>
                <div class="col-md-4">
                    <%= f.submit "vs AI", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
                </div>
                <div class="col-md-4">
                    <%= f.submit "Auto", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/pokemon_battles/show.html.erb
<div class="container">
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <div class="card-header bg-primary text-white">
            <h2 class="text-center">Pokemon Battle</h2>
        </div>
        <div class="card-body">
            <% if !@pokemon_battle.pokemon_winner_id.nil? %>
                <h2 class="text-center">Winners : <%= @pokemon_battle.winner.name %></h2>
            <% end %>
            <div class="row">
                <div class="col-4">
                    <div class="container">
                        <div class="card">
                            <%= image_tag @pokemon_battle.pokemon1.pokedex.image_url,size: "150x250", class: "card-img-top" %>
                            <div class="card-header form-header">
                                <h5 class="card-title text-center"><%= @pokemon_battle.pokemon1.name%></h5>
                            </div>
                            <%= form_for :attack, url: pokemon_battle_path(@pokemon_battle), method: :patch do |f|%>
                            <div class="card-body">
                                <div class="list-group list-group-flush">
                                    <div class="list-group-item">
                                        <div class="row">
                                            <div class="col-3 text-center">
                                                HP
                                            </div>
                                            <div class="col-9">
                                                : <%= @pokemon_battle.pokemon1.current_health_point %>/<%= @pokemon_battle.pokemon1_max_health_point %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="list-group-item">
                                        <div class="row">
                                            <div class="col-3 text-center">
                                                Skill
                                            </div>
                                            <div class="col-9">
                                                <%= f.select :skill_id, @skill1, {}, class: "form-control" %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center form-footer">
                                <%= f.hidden_field :pokemon_id, value: @pokemon_battle.pokemon1.id %>
                                <% if @pokemon_battle.current_turn % 2 == 0 %>
                                    <%= f.submit "Attack", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Surrender", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Auto", class: "btn btn-secondary", disabled: true%>
                                <% elsif !@pokemon_battle.pokemon_winner_id.nil?%>
                                    <%= f.submit "Attack", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Surrender", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Auto", class: "btn btn-secondary", disabled: true%>
                                <% else %>
                                    <%= f.submit "Attack", class: "btn btn-primary" %>
                                    <%= f.submit "Surrender", class: "btn btn-primary" %>
                                    <%= f.submit "Auto", class: "btn btn-secondary"%>
                                <% end %>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="d-flex align-items-center h-100">
                        <h2 class="mx-auto">Versus</h2>
                    </div> 
                </div>
                <div class="col-4">
                    <div class="container">
                        <div class="card card-height">
                            <%= image_tag @pokemon_battle.pokemon2.pokedex.image_url,size: "150x250" , class: "card-img-top" %>
                            <div class="card-header form-header">
                                <h5 class="card-title text-center"><%= @pokemon_battle.pokemon2.name%></h5>
                            </div>
                            <%= form_for :attack, url: pokemon_battle_path(@pokemon_battle), method: :patch do |f|%>
                            <%= f.hidden_field :pokemon_id, value: @pokemon_battle.pokemon2.id %>
                            <div class="card-body">
                                <div class="list-group list-group-flush">
                                    <div class="list-group-item">
                                        <div class="row">
                                            <div class="col-3 text-center">
                                                HP
                                            </div>
                                            <div class="col-9">
                                                : <%= @pokemon_battle.pokemon2.current_health_point %>/<%= @pokemon_battle.pokemon2_max_health_point %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="list-group-item">
                                        <div class="row">
                                            <div class="col-3 text-center">
                                                Skill
                                            </div>
                                            <div class="col-9">
                                                <%= f.select :skill_id, @skill2, {}, class: "form-control" %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center form-footer">
                                <% if @pokemon_battle.current_turn % 2 != 0 %>
                                    <%= f.submit "Attack", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Surrender", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Auto", class: "btn btn-secondary", disabled: true%>
                                <% elsif !@pokemon_battle.pokemon_winner_id.nil?%>
                                    <%= f.submit "Attack", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Surrender", class: "btn btn-primary", disabled: true %>
                                    <%= f.submit "Auto", class: "btn btn-secondary", disabled: true%>
                                <% else %>
                                    <%= f.submit "Attack", class: "btn btn-primary" %>
                                    <%= f.submit "Surrender", class: "btn btn-primary" %>
                                    <%= f.submit "Auto", class: "btn btn-secondary"%>
                                <% end %>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <div class="card-header bg-primary text-white">Pokemon Battle Logs</div>
        <div class="card-body">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr class="d-flex">
                        <th class="col-1 text-center">Turn</th>
                        <th class="col-2 text-center">Skill</th>
                        <th class="col-1 text-center">Damage</th>
                        <th class="col-2 text-center">Attacker</th>
                        <th class="col-1 text-center">Attacker Health Point</th>
                        <th class="col-2 text-center">Defender</th>
                        <th class="col-1 text-center">Defender Health Point</th>
                        <th class="col-2 text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @logs.each do |log| %>
                        <tr class="d-flex">
                            <td class="col-1 text-center"><%= log.turn %></td>
                            <td class="col-2 text-center">
                                <% if log.skill.nil? %>
                                -
                                <% else %>
                                <%= log.skill.name %>
                                <% end %>
                            </td>
                            <td class="col-1 text-center"><%= log.damage %></td>
                            <td class="col-2 text-center"><%= log.attacker.name %></td>
                            <td class="col-1 text-center"><%= log.attacker_current_health_point %></td>
                            <td class="col-2 text-center"><%= log.defender.name %></td>
                            <td class="col-1 text-center"><%= log.defender_current_health_point %></td>
                            <td class="col-2 text-center"><%= log.action_type %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/pokemon_battles/skill_change.html.erb
<div class="container container-border">
    <%= form_for :change_skill, url: change_skill_pokemon_battle_path(@pokemon_battle) do |f| %>
        <%= render 'layouts/error_messages', object: @pokemon_skill %>
        <div class="row form-header">
            <% if @pokemon_skills.count == 4 %>
                <h2 class="mx-auto">Change Skill ?</h2>
            <% else %>
                <h2 class="mx-auto">New Skill ?</h2>
            <% end %>
        </div>
        <% if @pokemon_skills.count == 4 %>
            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :skill_delete_id, class: "col-form-label" %>
                </div>
                <div class="col-8">
                    <%= f.select :skill_delete_id, @pokemon_skills, {:include_blank => true}, class: "form-control"  %>
                </div>
            </div>
        <% end %>
        <div class="form-row form-group">
             <div class="col-2">
                <%= f.label :skill_add_id, class: "col-form-label" %>
            </div>
            <div class="col-8">
                <%= f.select :skill_add_id, @skills, {:include_blank => true}, class: "form-control"  %>
            </div>
        </div>

        <div class="row form-footer">
            <%= f.submit "Submit", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
        </div>
    <% end %>
</div>