config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/heal', to: 'pokemons#healall'
  get '/heal/:id', to: 'pokemons#heal', as: 'heal_pokemon'
  get '/heal-trainer/:id', to: 'pokemon_trainers#healall', as: 'heal_trainer'
  get '/heal-trainer/:id/:pokemon_id', to: 'pokemon_trainers#heal', as: 'heal_trainer_pokemon'

  resources :pokedexes
  resources :skills
  resources :pokemons do
    resources :pokemon_skills, only: [:create, :destroy]
  end
  resources :pokemon_battles do
    member do
      get :evolve_confirmation
      post :evolve_confirmation, to: 'pokemon_battles#evolve'
      get :skill_change
      post :change_skill
    end
  end
  resources :trainers do
    resources :pokemon_trainers, only: [:create, :destroy]
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    belongs_to :pokedex
    has_many :pokemon_skills, foreign_key: "pokemon_id", dependent: :destroy
    has_many :skill, through: :pokemon_skills

    has_many :pokemon_battles, foreign_key: "pokemon1_id", dependent: :destroy
    has_many :pokemon_battles2, class_name: "PokemonBattle", foreign_key: "pokemon2_id", dependent: :destroy

    has_many :attacker, class_name: "PokemonBattleLog", foreign_key: "attacker_id"
    has_many :defender, class_name: "PokemonBattleLog", foreign_key: "defender_id"

    validates :name, length: { maximum: 45 }, presence: true, uniqueness: true
    validates :max_health_point, numericality: {greater_than: 0 }
    validates :current_health_point, numericality: { greater_than_or_equal_to: 0 }
    validates :current_health_point, numericality: { less_than_or_equal_to: :max_health_point },
                                     if: :max_health_point_present?
    validates :current_experience, numericality: {greater_than_or_equal_to: 0 }
    validates :attack, numericality: { greater_than: 0 }
    validates :defence, numericality: { greater_than: 0 }
    validates :speed, numericality: { greater_than: 0 }
    validates :level, numericality: { greater_than: 0 }
    
    def battles
        (pokemon_battles.all + pokemon_battles2.all).uniq
    end

    def wins
        sql = "
            select 
                count(pokemon_battles.pokemon_winner_id)
            from 
                pokemons
            join pokemon_battles 
                on (pokemon_battles.pokemon_winner_id = pokemons.id)
            where 
                pokemons.id = #{id}
            group by 
                pokemon_battles.pokemon_winner_id"
        win = ActiveRecord::Base.connection.execute(sql)
        if win.values[0].nil?
            win = 0
        else
            win = win.values[0][0]
        end
        win
    end

    def loses
        sql = "
            select 
                count(pokemon_battles.pokemon_loser_id)
            from 
                pokemons
            join pokemon_battles 
                on (pokemon_battles.pokemon_loser_id = pokemons.id)
            where 
                pokemons.id = #{id}
            group by 
                pokemon_battles.pokemon_loser_id"
        lose = ActiveRecord::Base.connection.execute(sql)
        if lose.values[0].nil?
            lose = 0
        else
            lose = lose.values[0][0]
        end
        lose
    end    

    private

    def max_health_point_present?
        max_health_point.present?
    end
    
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    add_breadcrumb "Home", :root_path
    add_breadcrumb "Pokemons", :pokemons_path

    def index
        @pokemons = Pokemon.paginate(page: params[:page], :per_page => 15).order(created_at: :asc)
    end

    def new
        @pokemon = Pokemon.new
        @pokedexes = Pokedex.all.map { |pokedex| [pokedex.name, pokedex.id]}
        add_breadcrumb "New", new_pokemon_path
    end

    def create
        params = pokemon_params
        pokedex = Pokedex.find(params['pokedex_id'])
        @pokemon = Pokemon.new(params)
        @pokemon.max_health_point = pokedex.base_health_point
        @pokemon.current_health_point = pokedex.base_health_point
        @pokemon.attack = pokedex.base_attack
        @pokemon.defence = pokedex.base_defence
        @pokemon.speed = pokedex.base_speed
        if @pokemon.save
            flash[:success] = "Pokemon #{@pokemon.name} successfully created"
            redirect_to pokemon_path(@pokemon)
        else
            @pokedexes = Pokedex.all.map { |pokedex| [pokedex.name, pokedex.id]}
            render :new
        end
    end

    def show
        @pokemon = Pokemon.find(params[:id])
        @current_skill = @pokemon.pokemon_skills.map{ |s| s.skill_id }
        @skills = Skill.all.select{ |s| !@current_skill.include?(s.id) && s.element_type == @pokemon.pokedex.element_type }
        .map{|s| [s.name, s.id]}
        # @skills = Skill.all.map { |skill| [skill.name, skill.id]}
        @pokemon_skill = PokemonSkill.new
        add_breadcrumb "#{@pokemon.name}", pokemon_path(@pokemon)
    end 

    def edit
        @pokemon = Pokemon.find(params[:id])
        add_breadcrumb "#{@pokemon.name}", pokemon_path(@pokemon)
        add_breadcrumb "Edit", edit_pokemon_path(@pokemon)
    end

    def update
        @pokemon = Pokemon.find(params[:id])
        if @pokemon.update_attributes(edit_params)
            flash[:success] = "Update Succesfull"
            redirect_to pokemon_path(@pokemon)
        else
            render :edit
        end
    end

    def destroy
        pokemon = Pokemon.find(params[:id]).destroy
        flash[:success] = "Pokemon deleted"
        redirect_to pokemons_path
    end

    def healall
        pokemons = Pokemon.all
        pokemons.each do |pokemon|
            pokemon_battle = pokemon.battles
            state = true
            pokemon_battle.each do |battle|
                if battle.state == 'On Going'
                    state = false
                    break
                end
            end
            if state == true
                pokemon.update!(current_health_point: pokemon.max_health_point)
                skills = pokemon.pokemon_skills
                skills.each do |skill|
                    skill.update!(current_pp: skill.skill.max_pp)
                end
            end
        end
        flash[:success] = "All Pokemon currently not in battle has been healed"
        redirect_to pokemons_path
    end

    def heal
        pokemon = Pokemon.find(params[:id])
        pokemon_battle = pokemon.battles
        state = true
        pokemon_battle.each do |battle|
            if battle.state == 'On Going'
                state = false
                break
            end
        end
        if state == true
            pokemon.update!(current_health_point: pokemon.max_health_point)
            skills = pokemon.pokemon_skills
            skills.each do |skill|
                skill.update!(current_pp: skill.skill.max_pp)
            end
            flash[:success] = "#{pokemon.name} has been healed"
        else
            flash[:danger] = "#{pokemon.name} can't be healed please make sure pokemon is not currently in battle"
        end
        redirect_to pokemons_path
    end

    private
    def pokemon_params
        params.require(:pokemon).permit(:name, :pokedex_id)
    end

    def edit_params
        params.require(:pokemon).permit(:name, :attack, :defence, :speed, :current_health_point, :max_health_point, :current_experience)
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/edit.html.erb
<div class="container">
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <%= form_for @pokemon do |f| %>
        <div class="card-header bg-primary text-white text-center">Edit Pokemon</div>
        
        <div class="card-body">
            <%= render 'layouts/error_messages', object: @pokemon %>
            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :name, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :max_health_point, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :max_health_point, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :current_health_point, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :current_health_point, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :attack, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :attack, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :defence, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :defence, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :speed, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :speed, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :level, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :level, class: 'form-control', disabled: true %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :current_experience, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :current_experience, class: 'form-control',disabled: true %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :pokedex_id, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :pokedex_id, class: 'form-control', disabled: true, value: @pokemon.pokedex.name %>
                </div>
            </div>
        </div>
        
        <div class="row card-footer">
            <%= f.submit "Update", class: "btn btn-primary btn-block" %>
        </div>
    <% end %>
    </div>
</div>

app/views/pokemons/index.html.erb
<div class="container">
    <div>
        <%= link_to "New Pokemon", new_pokemon_path, class: "btn btn-primary"%>
        <%= link_to "Heal All", heal_path, class: "btn btn-success"%>
    </div>

    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <div class="card-header bg-primary text-white">Pokemons</div>
        <div class="card-body">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr class="d-flex">
                        <th class="col-2 text-center">Name</th>
                        <th class="col-3 text-center">Image</th>
                        <th class="col-2 text-center">Level</th>
                        <th class="col-2 text-center">Health</th>
                        <th class="col-3 text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @pokemons.each do |pokemon| %>
                        <tr class="d-flex">
                            <td class="col-2 text-center"><%= pokemon.name %></td>
                            <td class="col-3 text-center"><%= image_tag pokemon.pokedex.image_url, size: "50x50" %></td>
                            <td class="col-2 text-center"><%= pokemon.level %></td>
                            <td class="col-2 text-center"><%= pokemon.current_health_point %>/<%= pokemon.max_health_point %></td>
                            <td class="col-3 text-center">
                            <%= link_to "Heal", heal_pokemon_path(pokemon), class: "btn btn-success"%>
                            <%= link_to "Show", pokemon_path(pokemon), class: "btn btn-info"%>
                            <%= link_to "Delete", pokemon_path(pokemon), method: :delete,
                                            data: { confirm: "You sure?" }, class: "btn btn-danger"%>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="clearfix card-footer">
            <%= will_paginate @pokemons, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "float-right" %>
        </div>
    </div>
</div>

app/views/pokemons/new.html.erb
<div class="container">
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <%= form_for @pokemon do |f| %>
        <div class="card-header bg-primary text-white text-center">New Pokemon</div>
        
        <div class="card-body">
            <%= render 'layouts/error_messages', object: @pokemon %>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :pokedex_id, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.select :pokedex_id, @pokedexes, {}, class: "form-control" %>
                </div>
            </div>
            
            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :name, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="row card-footer">
            <%= f.submit "Create", class: "btn btn-primary btn-block" %>
        </div>
    <% end %>
    </div>
</div>

app/views/pokemons/show.html.erb
<div class="container">
    <div>
        <%= link_to "Heal Pokemon", heal_pokemon_path(@pokemon), class: "btn btn-success btn-size"%>
        <%= link_to "Edit Pokemon", edit_pokemon_path(@pokemon), class: "btn btn-primary btn-size" %>
        <%= link_to "Delete Pokemon", pokemon_path(@pokemon), method: :delete, data: { confirm: "You sure?" } , class: "btn btn-danger btn-size" %>
    </div>
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <div class="card-header bg-primary border-primary text-white text-center"><%= @pokemon.name %></div>
        <div class="card-body">
            <div class="row" style="padding-top: 10px">
                <div class="col-md-5">
                    <%= image_tag @pokemon.pokedex.image_url%>
                </div>
                <div class="col-md-7">
                <br><br><br>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Level </h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= @pokemon.level %></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Health Point</h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= @pokemon.current_health_point %>/ <%= @pokemon.max_health_point %></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Attack </h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= @pokemon.attack %></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Defence </h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= @pokemon.defence %></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Speed </h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= @pokemon.speed %></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Current Experience </h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= @pokemon.current_experience %></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Pokedex </h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= link_to @pokemon.pokedex.name, pokedex_path(@pokemon.pokedex) %></h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <h3>Win/Lose </h3>
                        </div>
                        <div class="col-md-6">
                            <h3>: <%= @pokemon.wins %> / <%= @pokemon.loses %></h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="card border-info" style="margin-top: 15px; margin-bottom: 20px">
                    <div class="card-header bg-info text-white">Pokemon Skills</div>
                    <div class="card-body">
                        <div style="margin: 10px">
                            <%= render 'layouts/error_messages', object: @pokemon_skill %>
                        </div>
                        <table class="table table-hover">
                            <thead class="thead-light">
                            <tr class="d-flex">
                                <th class="col-4 text-center">Name</th>
                                <th class="col-4 text-center">Current PP</th>
                                <th class="col-4 text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                <% @pokemon.pokemon_skills.each do |pokemon_skill| %>
                                    <tr class="d-flex">
                                        <td class="col-4 text-center"><%= pokemon_skill.skill.name %></td>
                                        <td class="col-4 text-center"><%= pokemon_skill.current_pp %>/ <%= pokemon_skill.skill.max_pp %></td>
                                        <td class="col-4 text-center">
                                        <%= link_to "Delete", pokemon_pokemon_skill_path(@pokemon, pokemon_skill), method: :delete,
                                                        data: { confirm: "You sure?" }, class: "btn btn-danger"%>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <%= form_for :pokemon_skill, url: pokemon_pokemon_skills_path(@pokemon) do |f| %>
                        <div class="form-row form-group">
                            <div class="col-2">
                                <%= f.label :skill_id, class: "col-form-label" %>
                            </div>
                            <div class="col-8">
                                <%= f.select :skill_id, @skills, {:include_blank => true}, class: "form-control"  %>
                            </div>
                            <div class="col-2">
                                <%= f.submit "Add Skill", class: "btn btn-primary btn-block" %>
                            </div>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>