config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/heal', to: 'pokemons#healall'
  get '/heal/:id', to: 'pokemons#heal', as: 'heal_pokemon'
  get '/heal-trainer/:id', to: 'pokemon_trainers#healall', as: 'heal_trainer'
  get '/heal-trainer/:id/:pokemon_id', to: 'pokemon_trainers#heal', as: 'heal_trainer_pokemon'

  resources :pokedexes
  resources :skills
  resources :pokemons do
    resources :pokemon_skills, only: [:create, :destroy]
  end
  resources :pokemon_battles do
    member do
      get :evolve_confirmation
      post :evolve_confirmation, to: 'pokemon_battles#evolve'
      get :skill_change
      post :change_skill
    end
  end
  resources :trainers do
    resources :pokemon_trainers, only: [:create, :destroy]
  end
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    before_save   :downcase_email
    has_many :pokemon_trainers, dependent: :destroy
    has_many :pokemons, through: :pokemon_trainers

    has_secure_password
    validates :email, uniqueness: { case_sensitive: false }, presence: true
    validates :name, presence: true

    def downcase_email
        self.email = email.downcase
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    add_breadcrumb "Home", :root_path
    add_breadcrumb "Trainers", :trainers_path

    def index
        @trainers = Trainer.paginate(page: params[:page], :per_page => 15)
    end

    def new
        @trainer = Trainer.new
        add_breadcrumb "New", new_trainer_path
    end

    def create
        @trainer = Trainer.new(trainer_params)
        if @trainer.save
            flash[:success] = "#{@trainer.name} successfully created"
            redirect_to trainer_path(@trainer)
        else
            render :new
        end
    end

    def show
        @name = params[:name]
        if @name.nil?
            @name = 'pokemon'
        end
        @trainer = Trainer.find(params[:id])
        if @name == 'pokemon'
            @pokemon_trainer = PokemonTrainer.new
            @used_pokemons = PokemonTrainer.all.map { |pokemon| pokemon.pokemon_id }
            @pokemons = Pokemon.all.select{ |pokemon| !@used_pokemons.include?(pokemon.id)}
            .map{|pokemon| [pokemon.name, pokemon.id]}
        else
            @top_winner = PokemonTrainerStatistic.top_winner(params[:id])
            @top_loser = PokemonTrainerStatistic.top_loser(params[:id])
            @top_battle = PokemonTrainerStatistic.top_battle(params[:id])
            @win_rate = PokemonTrainerStatistic.win_rate(params[:id])
            @element_rate = PokemonTrainerStatistic.element_rate(params[:id])
        end
        add_breadcrumb "#{@trainer.name}", trainer_path(@trainer)
    end

    def edit
        @trainer = Trainer.find(params[:id])
        add_breadcrumb "#{@trainer.name}", trainer_path(@trainer)
        add_breadcrumb "Edit", edit_trainer_path(@trainer)
    end

    def update
        @trainer = Trainer.find(params[:id])
        if @trainer.update_attributes(update_params)
            flash[:success] = "Update Succesfull"
            redirect_to trainer_path(@trainer)
        else
            render :edit
        end
    end

    def destroy
        trainer = Trainer.find(params[:id]).destroy
        flash[:success] = "Trainer deleted"
        redirect_to trainers_path
    end

    private
    def trainer_params
        params.require(:trainer).permit(:name, :email, :password)
    end

    def update_params
        params.require(:trainer).permit(:name, :email)
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/edit.html.erb
<div class="container">
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <%= form_for @trainer do |f| %>
        <div class="card-header bg-primary text-white border-primary">
            <div class="text-center">Edit Trainer</div>
        </div>
        <div class="card-body">
            <%= render 'layouts/error_messages', object: @trainer %>
            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :name, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :email, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.email_field :email, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="row card-footer">
            <%= f.submit "Update", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
        </div>
        <% end %>
    </div>
</div>

app/views/trainers/index.html.erb
<div class="container">
    <div>
        <%= link_to "New Trainer", new_trainer_path, class: "btn btn-primary"%>
    </div>

    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <div class="card-header bg-primary text-white">Trainers</div>
        <div class="card-body">
            <table class="table table-hover">
                <thead class="thead-light">
                    <tr class="d-flex">
                        <th class="col-4 text-center">Name</th>
                        <th class="col-4 text-center">Email</th>
                        <th class="col-4 text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @trainers.each do |trainer| %>
                        <tr class="d-flex">
                            <td class="col-4 text-center"><%= trainer.name %></td>
                            <td class="col-4 text-center"><%= trainer.email %></td>
                            <td class="col-4 text-center">
                            <%= link_to "Show", trainer_path(trainer), class: "btn btn-info"%>
                            <%= link_to "Delete", trainer_path(trainer), method: :delete,
                                            data: { confirm: "You sure?" }, class: "btn btn-danger"%>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <div class="clearfix card-footer">
            <%= will_paginate @trainers, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "float-right" %>
        </div>
    </div>
</div>

app/views/trainers/new.html.erb
<div class="container">
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <%= form_for @trainer do |f| %>
        <div class="card-header bg-primary text-white">
            <div class="text-center">New Trainer</div>
        </div>
        <div class="card-body">
            <%= render 'layouts/error_messages', object: @trainer %>
            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :name, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :email, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.email_field :email, class: 'form-control' %>
                </div>
            </div>

            <div class="form-row form-group">
                <div class="col-2">
                    <%= f.label :password, class: "col-form-label" %>
                </div>
                <div class="col-10">
                    <%= f.password_field :password, class: 'form-control' %>
                </div>
            </div>
        </div>
        <div class="row card-footer">
            <%= f.submit "Create", class: "btn btn-primary btn-block", :style => 'margin-top: 14px' %>
        </div>
        <% end %>
    </div>
</div>

app/views/trainers/show.html.erb
<div class="container">
    <div>
        <%= link_to "Edit Trainer", edit_trainer_path(@trainer), class: "btn btn-primary btn-size" %>
        <%= link_to "Delete Trainer", trainer_path(@trainer), method: :delete, data: { confirm: "You sure?" } , class: "btn btn-danger btn-size" %>
    </div>
    <div class="card border-primary" style="margin-top: 15px; margin-bottom: 20px">
        <div class="card-header bg-primary border-primary text-white text-center">Trainer</div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <h2>Name </h2>
                </div>
                <div class="col-md-6">
                    <h2>: <%= @trainer.name %></h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h2>Email </h2>
                </div>
                <div class="col-md-6">
                    <h2>: <%= @trainer.email %></h2>
                </div>
            </div>
        </div>
        <ul class="nav nav-pills justify-content-center">
            <li class="nav-item">
                <%= link_to "Pokemon", trainer_path(@trainer, { name: 'pokemon'}), class: "nav-link #{@name == 'pokemon' ? 'active' : ''}" %>
            </li>
            <li class="nav-item">
                <%= link_to "Statistic", trainer_path(@trainer, { name: "statistic"}), class: "nav-link #{@name == 'statistic' ? 'active' : ''}" %>
            </li>
        </ul>
        <% if @name == 'pokemon' %>
            <div class="container">
                <div class="card border-info" style="margin-top: 15px; margin-bottom: 20px">
                    <div class="card-header bg-info border-primary text-white">My Pokemons</div>
                    <div class="card-body">
                        <div style="margin: 10px">
                            <%= link_to "Heal All", heal_trainer_path(@trainer), class: "btn btn-success"%>
                            <%= render 'layouts/error_messages', object: @pokemon_trainer %>
                        </div>
                        <table class="table table-hover">
                            <thead class="thead-light">
                                <tr class="d-flex">
                                    <th class="col-2 text-center">Name</th>
                                    <th class="col-2 text-center">Image</th>
                                    <th class="col-2 text-center">Win/Lose</th>
                                    <th class="col-2 text-center">Win Rate</th>
                                    <th class="col-2 text-center">HP</th>
                                    <th class="col-2 text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @trainer.pokemon_trainers.each do |pokemon_trainer| %>
                                    <tr class="d-flex">
                                        <td class="col-2 text-center"><%= link_to pokemon_trainer.pokemon.name, pokemon_path(pokemon_trainer.pokemon), class: "btn btn-link" %></td>
                                        <td class="col-2 text-center"><%= image_tag pokemon_trainer.pokemon.pokedex.image_url, size: "50x50" %></td>
                                        <td class="col-2 text-center"><%= pokemon_trainer.win %> / <%= pokemon_trainer.lose %></td>
                                        <td class="col-2 text-center"><%= pokemon_trainer.win_rate %>%</td>
                                        <td class="col-2 text-center"><%= pokemon_trainer.pokemon.current_health_point %>/<%= pokemon_trainer.pokemon.max_health_point %></td>
                                        <td class="col-2 text-center">
                                        <%= link_to "Heal", heal_trainer_pokemon_path(@trainer, pokemon_trainer.pokemon), class: "btn btn-success"%>
                                        <%= link_to "Delete", trainer_pokemon_trainer_path(@trainer, pokemon_trainer), method: :delete,
                                                        data: { confirm: "You sure?" }, class: "btn btn-danger"%>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <%= form_for :pokemon_trainer, url: trainer_pokemon_trainers_path(@trainer) do |f| %>
                            <div class="form-row form-group">
                                <div class="col-2">
                                    <%= f.label :pokemon_id, class: "col-form-label" %>
                                </div>
                                <div class="col-8">
                                    <%= f.select :pokemon_id, @pokemons, {}, class: "form-control"  %>
                                </div>
                                <div class="col-2">
                                    <%= f.submit "Add Pokemon", class: "btn btn-primary btn-block" %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>

        <% if @name == 'statistic' %>
        <div class="container">
            <div class="card border-info" style="margin-top: 15px; margin-bottom: 20px">
                <div class="card-header bg-info text-white">Trainer Statistic</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card border-secondary" style="margin-top: 15px; margin-bottom: 20px">
                                <div class="card-body">
                                    <%= column_chart @top_winner,
                                        title: "Pokemon Win Count",
                                        colors: ['blue'],
                                        library: {
                                            yAxis: {
                                            allowDecimals: false,
                                            title: {
                                                text: "Wins"
                                            }
                                            },
                                            xAxis: {
                                            title: {
                                                text: "Pokemon Name"
                                            }
                                            },
                                            tooltip: {
                                                backgroundColor: '#FCFFC5',
                                                borderColor: 'blue',
                                                borderRadius: 10,
                                                borderWidth: 3
                                            }
                                        },
                                        messages: {empty: "Pokemon Win Count :No data"}
                                    %>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card border-secondary" style="margin-top: 15px; margin-bottom: 20px">
                                <div class="card-body">
                                <%= bar_chart @top_loser,
                                    title: "Pokemon Lose Count",
                                    colors: ['red'],
                                    ytitle: 'Lose',
                                    xtitle: 'Pokemon Name',
                                    messages: {empty: "Pokemon Lose Count: No data"}
                                %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card border-secondary" style="margin-top: 15px; margin-bottom: 20px">
                                <div class="card-body">
                                <%= line_chart @top_battle,
                                    title: "Pokemon Battle Count",
                                    colors: ['red'],
                                    ytitle: 'Used',
                                    xtitle: 'Pokemon Name',
                                    messages: {empty: "Pokemon Battle Count: No data"}
                                %>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card border-secondary" style="margin-top: 15px; margin-bottom: 20px">
                                <div class="card-body">
                                <%= pie_chart @win_rate,
                                    title: "Pokemon Win Rate",
                                    ytitle: 'Used',
                                    xtitle: 'Pokemon Name',
                                    suffix: '%',
                                    messages: {empty: "Pokemon Win Rate: No data"}
                                %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card border-secondary" style="margin-top: 15px; margin-bottom: 20px">
                                <div class="card-body">
                                <%= column_chart @element_rate,
                                    title: "Trainer Pokemon Element Rate",
                                    colors: ['green'],
                                    xtitle: 'Element',
                                    suffix: '%',
                                    library: {
                                        yAxis: {
                                            title: {
                                                text: "Count"
                                            }
                                        }
                                    },
                                    messages: {empty: "Trainer Pokemon Element Rate: No data"}
                                %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>