config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/heal', to: 'pokemons#healall'
  get '/heal/:id', to: 'pokemons#heal', as: 'heal_pokemon'
  get '/heal-trainer/:id', to: 'pokemon_trainers#healall', as: 'heal_trainer'
  get '/heal-trainer/:id/:pokemon_id', to: 'pokemon_trainers#heal', as: 'heal_trainer_pokemon'

  resources :pokedexes
  resources :skills
  resources :pokemons do
    resources :pokemon_skills, only: [:create, :destroy]
  end
  resources :pokemon_battles do
    member do
      get :evolve_confirmation
      post :evolve_confirmation, to: 'pokemon_battles#evolve'
      get :skill_change
      post :change_skill
    end
  end
  resources :trainers do
    resources :pokemon_trainers, only: [:create, :destroy]
  end
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>:
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small bg-secondary">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://github.com/alvingho25/pokemon-rainbow-ukirama" class="text-white"> Alvin</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-secondary navbar-dark">
  <%= link_to "Pokemon Rainbow", root_path, class: "navbar-brand" %>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to "Battle", pokemon_battles_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Pokemon", pokemons_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Pokedex", pokedexes_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Skills", skills_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Trainers", trainers_path, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonRainbow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" style="padding-top:10px">
      <ol class="breadcrumb">
        <%= render_breadcrumbs :tag => :li, :separator => '&nbsp;/&nbsp;' %>
      </ol>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> 
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>